import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  IMPORTANT_NODES,
  MAX_PLAN_ACTIONS,
  MAX_ROUTE_STEPS,
  buildRouteTable,
  buildPlanForLayout,
  createDefaultPlanningConfig,
  enumerateLegalLayouts
} from "./stm32Shared";
import type { EnumeratedLayout, GeneratedPlanDesc, GeneratedRouteEntry } from "./stm32Shared";
import type { SimulationConfig } from "./types";

export { MAX_PLAN_ACTIONS, buildPlanForLayout, createDefaultPlanningConfig, enumerateLegalLayouts } from "./stm32Shared";

const BRANCHES = ["RED", "YELLOW", "BLUE", "GREEN"] as const;
const COLORS = ["RED", "YELLOW", "BLUE", "GREEN"] as const;

export interface Stm32TablesData {
  layouts: EnumeratedLayout[];
  planTable: GeneratedPlanDesc[];
  planTableLiFo: GeneratedPlanDesc[];
  routeTable: Record<string, Record<string, GeneratedRouteEntry>>;
  importantNodes: readonly string[];
}

let cachedTablesData: Stm32TablesData | null = null;

function computePlanTable(config: SimulationConfig, layouts: EnumeratedLayout[], mode: "normal" | "lifo"): GeneratedPlanDesc[] {
  return layouts.map((layout) => buildPlanForLayout(config, layout, mode));
}

function computeRouteTable(config: SimulationConfig): Record<string, Record<string, GeneratedRouteEntry>> {
  return buildRouteTable(config);
}

export function buildStm32TablesData(): Stm32TablesData {
  if (cachedTablesData) {
    return cachedTablesData;
  }
  const config = createDefaultPlanningConfig();
  const layouts = enumerateLegalLayouts();
  const planTable = computePlanTable(config, layouts, "normal");
  const planTableLiFo = computePlanTable(config, layouts, "lifo");
  const routeTable = computeRouteTable(config);
  cachedTablesData = {
    layouts,
    planTable,
    planTableLiFo,
    routeTable,
    importantNodes: IMPORTANT_NODES
  };
  return cachedTablesData;
}

function renderEnum(name: string, items: readonly string[], transform?: (item: string) => string): string {
  const values = items.map((item) => `  ${transform ? transform(item) : item},`).join("\n");
  return `typedef enum {\n${values}\n  ${name.toUpperCase()}_COUNT\n} ${name};`;
}

function renderHeaderBanner(source: string): string {
  return `/* Auto-generated by ${source}. Do not edit manually. */`;
}

function renderLayoutsHeader(): string {
  return `${renderHeaderBanner("src/generateStm32Tables.ts")}
#ifndef GENERATED_LAYOUTS_H
#define GENERATED_LAYOUTS_H

#include <stdint.h>

${renderEnum("branch_id_t", BRANCHES, (branch) => `BRANCH_${branch}`)}

${renderEnum("color_id_t", COLORS, (color) => `COLOR_${color}`)}

typedef struct {
    uint8_t slots[4][2];
} layout_desc_t;

extern const uint16_t g_layout_count;
extern const layout_desc_t g_layouts[576];

#endif
`;
}

function renderLayoutsSource(layouts: EnumeratedLayout[]): string {
  const rows = layouts
    .map((layout) => {
      const slots = BRANCHES.map((branch) => {
        const [slot1, slot2] = layout.slots[branch];
        return `{ COLOR_${slot1}, COLOR_${slot2} }`;
      }).join(", ");
      return `    { .slots = { ${slots} } }`;
    })
    .join(",\n");

  return `${renderHeaderBanner("src/generateStm32Tables.ts")}
#include "generated_layouts.h"

const uint16_t g_layout_count = 576;
const layout_desc_t g_layouts[576] = {
${rows}
};
`;
}

function renderPlanHeader(): string {
  return `${renderHeaderBanner("src/generateStm32Tables.ts")}
#ifndef GENERATED_PLAN_TABLE_H
#define GENERATED_PLAN_TABLE_H

#include <stdint.h>
#include "generated_layouts.h"

typedef enum {
  ACT_PICK_LOCK,
  ACT_DROP_LOCK,
  ACT_PICK_RESOURCE,
  ACT_DROP_RESOURCE,
  ACT_RETURN_START,
  ACT_END_ROUND,
  ACTION_TYPE_T_COUNT
} action_type_t;

#define MAX_PLAN_ACTIONS ${MAX_PLAN_ACTIONS}

typedef struct {
    uint8_t type;
    uint8_t arg0;
    uint8_t arg1;
} plan_action_t;

typedef struct {
    uint8_t action_count;
    plan_action_t actions[MAX_PLAN_ACTIONS];
} plan_desc_t;

extern const plan_desc_t g_plan_table[576];

#endif
`;
}

function renderPlanSource(planTable: GeneratedPlanDesc[]): string {
  const plans = planTable
    .map((plan) => {
      const actionRows = Array.from({ length: MAX_PLAN_ACTIONS }, (_, index) => {
        const action = plan.actions[index];
        if (!action) {
          return "{ ACT_END_ROUND, 0, 0 }";
        }
        return `{ ${action.type}, ${action.arg0}, ${action.arg1} }`;
      }).join(", ");
      return `    { .action_count = ${plan.action_count}, .actions = { ${actionRows} } }`;
    })
    .join(",\n");

  return `${renderHeaderBanner("src/generateStm32Tables.ts")}
#include "generated_plan_table.h"

const plan_desc_t g_plan_table[576] = {
${plans}
};
`;
}

function renderPlanLiFoHeader(): string {
  return `${renderHeaderBanner("src/generateStm32Tables.ts")}
#ifndef GENERATED_PLAN_TABLE_LIFO_H
#define GENERATED_PLAN_TABLE_LIFO_H

#include <stdint.h>
#include "generated_plan_table.h"

extern const plan_desc_t g_plan_table_lifo[576];

#endif
`;
}

function renderPlanLiFoSource(planTable: GeneratedPlanDesc[]): string {
  const plans = planTable
    .map((plan) => {
      const actionRows = Array.from({ length: MAX_PLAN_ACTIONS }, (_, index) => {
        const action = plan.actions[index];
        if (!action) {
          return "{ ACT_END_ROUND, 0, 0 }";
        }
        return `{ ${action.type}, ${action.arg0}, ${action.arg1} }`;
      }).join(", ");
      return `    { .action_count = ${plan.action_count}, .actions = { ${actionRows} } }`;
    })
    .join(",\n");

  return `${renderHeaderBanner("src/generateStm32Tables.ts")}
#include "generated_plan_table_lifo.h"

const plan_desc_t g_plan_table_lifo[576] = {
${plans}
};
`;
}

function renderRoutesHeader(): string {
  return `${renderHeaderBanner("src/generateStm32Tables.ts")}
#ifndef GENERATED_ROUTES_H
#define GENERATED_ROUTES_H

#include <stdint.h>

${renderEnum("node_id_t", IMPORTANT_NODES, (node) => `NODE_${node}`)}

typedef enum {
  STEP_STRAIGHT,
  STEP_LEFT,
  STEP_RIGHT,
  STEP_ENTER_BRANCH,
  STEP_STOP_ON_MARKER,
  ROUTE_STEP_T_COUNT
} route_step_t;

#define MAX_ROUTE_STEPS ${MAX_ROUTE_STEPS}

typedef struct {
    uint8_t valid;
    uint8_t step_count;
    uint8_t steps[MAX_ROUTE_STEPS];
} route_entry_t;

extern const route_entry_t g_route_table[NODE_ID_T_COUNT][NODE_ID_T_COUNT];

#endif
`;
}

function renderRoutesSource(routeTable: Record<string, Record<string, GeneratedRouteEntry>>): string {
  const rows = IMPORTANT_NODES.map((fromNode) => {
    const columns = IMPORTANT_NODES.map((toNode) => {
      const entry = routeTable[fromNode][toNode];
      const steps = Array.from({ length: MAX_ROUTE_STEPS }, (_, index) => entry.steps[index] ?? "STEP_STOP_ON_MARKER").join(", ");
      return `{ ${entry.valid}, ${entry.step_count}, { ${steps} } }`;
    }).join(", ");
    return `    { ${columns} }`;
  }).join(",\n");

  return `${renderHeaderBanner("src/generateStm32Tables.ts")}
#include "generated_routes.h"

/* Route steps are derived from node paths as a first-pass junction abstraction. */
const route_entry_t g_route_table[NODE_ID_T_COUNT][NODE_ID_T_COUNT] = {
${rows}
};
`;
}

export function renderStm32Tables(data: Stm32TablesData): Record<string, string> {
  return {
    "generated_layouts.h": renderLayoutsHeader(),
    "generated_layouts.c": renderLayoutsSource(data.layouts),
    "generated_plan_table.h": renderPlanHeader(),
    "generated_plan_table.c": renderPlanSource(data.planTable),
    "generated_plan_table_lifo.h": renderPlanLiFoHeader(),
    "generated_plan_table_lifo.c": renderPlanLiFoSource(data.planTableLiFo),
    "generated_routes.h": renderRoutesHeader(),
    "generated_routes.c": renderRoutesSource(data.routeTable)
  };
}

export function generateStm32Tables(outDir = join(process.cwd(), "generated", "stm32")): void {
  const data = buildStm32TablesData();
  const files = renderStm32Tables(data);
  mkdirSync(outDir, { recursive: true });
  for (const [name, contents] of Object.entries(files)) {
    writeFileSync(join(outDir, name), contents);
  }
  console.log("STM32 tables written to", outDir);
}

if (import.meta.url === `file://${process.argv[1]}`) {
  generateStm32Tables();
}
